### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by bradley-holt** [ibm-cds-labs/pipes#1]
In `package.json`, the `license` is listed as `IBM`. This triggers the following warning when doing an `npm install`:

```
npm WARN package.json pipes@0.1.0 license should be a valid SPDX license expression
```

Consider using `Apache 2.0` instead, as this license is commonly used for sample applications from IBM.

**Comment by DTAIEB** [comment]
What's the status on that one? Apache 2.0 looks good to me. @bradley-holt @bradnoble @maston @jessmantaro @AliceinCodingland

**Comment by AliceinCodingland** [comment]
@bradley-holt I'm 99% sure that Apache 2.0 was approved and that we have the license. I'm going to go try to find the documentation that I remember seeing and confirm, but Apache 2.0 should be good to go.

**Comment by AliceinCodingland** [comment]
@bradley-holt Sarah just confirmed that she added Apache 2.0 so we can go ahead and use it for the package.json. We will need to rename the tag since that's throwing an error

**Comment by bradley-holt** [comment]
Updated license to Apache 2 in 555011cbb22dde833d4fc960519a61d791f2dfcf.
