### ISSUE TITLE
Monitoring Dataworks Activities for Completion hung; did not finish

### ISSUE THREAD

**Issue by AliceinCodingland** [ibm-cds-labs/pipes#10]

**Comment by AliceinCodingland** [comment]
Generates, does not run

**Comment by AliceinCodingland** [comment]
Upon first run makes it, second run starts it

**Comment by AliceinCodingland** [comment]
Nothing completes

**Comment by DTAIEB** [comment]
Looking at the dataworks UI, it seems like all the dw activities have been created correctly but they are stuck in submitted mode. This is a problem with dataworks server that probably needs to be rebooted. We need to write an issue against DataWorks.
