### ISSUE TITLE
Can not connect to SF with Oath - sandbox checked

### ISSUE THREAD

**Issue by maston** [ibm-cds-labs/pipes#17]
got the following error connecting to SF:
error=invalid_client_id&error_description=client%20identifier%20invalid

What happened:
On a new deployment I was setting up OAuth.
Entereid the key and secret from the cloudant test bed.  
I clicked the sandbox checkbox.
The connecting modal appeared but then got this error.

**Comment by maston** [comment]
Doesn't work for login.salesforce.com or test.salesforce.com flow.  (tried to connect to both types)

**Comment by maston** [comment]
![image](https://cloud.githubusercontent.com/assets/6386422/8783550/9e1d5850-2eea-11e5-86e7-44dafaac1624.png)
Tried full redeploy.  It isn't writing the loginUrl to cloudant.

**Comment by DTAIEB** [comment]
I made a change to not use the default port (80 for http and 443 for https) in the callback. Another observation, is that you will need to wait for up to 10 mns for a newly created app on salesforce web site to be activated. After waiting long enough, the connection started to work. This needs to be documented in the tutorial.
