### ISSUE TITLE
Minor - Text update on app's Schedule tab

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/pipes#21]
Instructs say to click **next** but there is no next.  Edit to match button text and say "click **Skip** " instead.
![schedule_text](https://cloud.githubusercontent.com/assets/12279008/9141871/ddd32358-3d09-11e5-9c34-b2bdd43b8943.png)

**Comment by DTAIEB** [comment]
Fixed in multi-connector branch.
