### ISSUE TITLE
pipes.json example in "running locally" can cause copy/paste related problems

### ISSUE THREAD

**Issue by johnnason** [ibm-cds-labs/pipes#26]
Refer to https://github.com/ibm-cds-labs/pipes/wiki/Instructions-for-setting-up-a-local-dev-environment-for-Simple-Data-Pipe

1. Create a file called pipes.json in the same directory with the following contents:

The example that is given has two problems that will mean someone just copying the example will fail to run the app.
1) there should not be comments in the example
2) there is a trailing comma that causes problems

**Comment by DTAIEB** [comment]
Fixed. Added note to not copy the comments.
