### ISSUE TITLE
UI: Fit and finish

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pipes#39]
1. [Enhancements] - Activity tab
 - tables should be sorted alphabetically
 - record counts should be right aligned and formatted ("1234       " -->  "    1,234")

2. [bug] It should not be possible to select "Pick tables", "schedule" and "activity" tabs until connectivity details have been entered.

3. [bug] One can start a pipe run without having to select a table (or all tables). DataWorks activites are scheduled and process every staging cloudant database from previous runs. Example: run 1: copy data for customer table. Wait for pipe to finish. Create new pipe,  don't select a table and run the pipe. DataWorks will process the customer table. (We could just make "All Tables" the default selection to avoid this.)

4. [bug] There's always a dummy pipe named Pipe1 present.

5. [bug] One can enter a very long pipe name. The pipe name is not properly displayed in various places.

6. [bug] One can create multiple pipes with the same name.

7. [bug] One can **Connect to** salesforce/stripe without having to enter a consumer key or secret.

9. (Usability): It's not clear what time zone is used by the scheduler. Local time (of the end-user), local time in the Bluemix region or some other fixed time zone.

**Comment by vabarbosa** [comment]
following has been addressed in subsequent updates:
~~2. [bug] It should not be possible to select "Pick tables", "schedule" and "activity" tabs until connectivity details have been entered.~~
~~4. [bug] There's always a dummy pipe named Pipe1 present.~~
~~7. [bug] One can Connect to salesforce/stripe without having to enter a consumer key or secret.~~

**Comment by vabarbosa** [comment]
the following have been resolved:
~~5. [bug] One can enter a very long pipe name. The pipe name is not properly displayed in various places.~~
~~6. [bug] One can create multiple pipes with the same name.~~

**Comment by vabarbosa** [comment]
the following have been resolved:
~~1. [Enhancements] - Activity tab
    tables should be sorted alphabetically
    record counts should be right aligned and formatted ("1234 " --> " 1,234")~~
~~8. (Usability): It's not clear what time zone is used by the scheduler. Local time (of the end-user), local time in the Bluemix region or some other fixed time zone.~~
