### ISSUE TITLE
Stripe "charge" shows in dashDB as an "Event"

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/pipes#44]
Following successful pipe run (whoohoo!) Table charges was missing in dashDB (appeared in Cloudant).
In DataWorks, this table listed as "Finished with errors"
No error registered for the run though -- hidden failure

**Comment by ptitzler** [comment]
There's a document I started at that describes the mapping between stripe objects and tables in dashDB: https://github.com/ibm-cds-labs/pipes/wiki/How-to-access-your-stripe-data-on-dashDB.

**Comment by ptitzler** [comment]
Closing this issue. At this point we cannot determine if dataworks encountered an issue that prevented creation and population of the table in dashdb. We'll review the framework implementation to make sure failures are raised properly in the UI.
