### ISSUE TITLE
deleting a pipe does not delete corresponding runs

### ISSUE THREAD

**Issue by vabarbosa** [ibm-cds-labs/pipes#46]
when a pipe is deleted its corresponding runs are not deleted.
you can notice this when viewing the run/activity for all pipes.
the tables shows run for pipes which have been deleted.

**Comment by ptitzler** [comment]
Assumptions:
-  A pipe can only be deleted if it is not associated with any runs, or if all associated runs are in FINISHED, STOPPED or ERROR state.
- Individual pipe runs cannot be deleted.
- if a problem is encountered deleteing one or more pipe runs, the pipe is not deleted.

**Comment by ptitzler** [comment]
Delivered. I ran the following tests:
* Delete a pipe that wasn't run yet
* Delete a pipe while no run is in progress (multiple runs were completed before)
* Try to delete a pipe with while a run is in progress
