### ISSUE TITLE
Deploy to Bluemix failing on binding SSO service

### ISSUE THREAD

**Issue by maston** [ibm-cds-labs/pipes#5]
Tried to deploy to my account in a space.  (this is attempt #2) 

Error log attached.

Started by user pipeline
Building remotely on jenkins-deploy-slave-4a4f4571b1be (.*Deploy) in workspace /home/jenkins/workspace/cdb5e1ed-e7a4-8885-e80c-3b5d1fa01335/9ae6eded-052b-494e-b132-32dcfd11f503
Unable to access upstream artifacts area /jenkins/jobs/cdb5e1ed-e7a4-8885-e80c-3b5d1fa01335/jobs/9778a168-056f-43d5-99ec-cf41b82763ce/builds/2015-07-14_12-37-49/archive. Does source project archive artifacts?
Downloading artifacts ...
DOWNLOAD SUCCESSFUL
Total time: 1 seconds
[9ae6eded-052b-494e-b132-32dcfd11f503] $ /bin/bash /tmp/hudson9206519648023796782.sh
+ cat /etc/lsb-release /etc/os-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
+ cf --version
/usr/bin/cf-orig/cf version 6.7.0-IDS-2014-12-04T10:56:46+00:00
+ echo 'Target: https://api.ng.bluemix.net'
Target: https://api.ng.bluemix.net
+ source _deploy.sh
++ cf push simpleDataPipe2
Using manifest file /home/jenkins/workspace/cdb5e1ed-e7a4-8885-e80c-3b5d1fa01335/9ae6eded-052b-494e-b132-32dcfd11f503/manifest.yml

Creating app simpleDataPipe2 in org smaston@us.ibm.com / space SDP as smaston@us.ibm.com...
OK

Using route simpleDataPipe2.mybluemix.net
Binding simpleDataPipe2.mybluemix.net to simpleDataPipe2...
OK

Uploading simpleDataPipe2...
Uploading app files from: /home/jenkins/workspace/cdb5e1ed-e7a4-8885-e80c-3b5d1fa01335/9ae6eded-052b-494e-b132-32dcfd11f503
Uploading 307.7K, 75 files

                             
Done uploading
OK
Binding service pipes-cloudant-service to app simpleDataPipe2 in org smaston@us.ibm.com / space SDP as smaston@us.ibm.com...
OK
Binding service pipes-dashdb-service to app simpleDataPipe2 in org smaston@us.ibm.com / space SDP as smaston@us.ibm.com...
OK
Binding service pipes-dataworks-service to app simpleDataPipe2 in org smaston@us.ibm.com / space SDP as smaston@us.ibm.com...
OK
Binding service pipes-sso-service to app simpleDataPipe2 in org smaston@us.ibm.com / space SDP as smaston@us.ibm.com...
FAILED
Could not bind to service pipes-sso-service
Error: Server error, status code: 502, error code: 10001, message: Service broker error: {"description"=>"CTJSO0046E This application type could not be determined. Ensure that the application is staged or running and retry the operation."}
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by maston** [comment]
Error i get trying to bind SSO (it is in my BM with new Pipes app that can run)

Service broker error: {"description"=>"CTJSO0015E The service instance with ID \"3f44a704-da24-480a-a0d6-87d33d433459\" must be configured before the operation can be performed."}

**Comment by DTAIEB** [comment]
This may be a limitation of SSO service. I suggest we remove the SSO reference until I get a chance to investigate

**Comment by bradley-holt** [comment]
Temporarily removed SSO service binding in 7f89ff38cbb67d8f6ce8408c06b8d7f10d703817.

**Comment by bradley-holt** [comment]
I suspect that this is a chicken-and-egg problem. The SSO service may need the app to be started to bind, and the app needs SSO to be bound in order to start.

**Comment by maston** [comment]
@DTAIEB is this good to close?
