### ISSUE TITLE
Local dev environment breaks with absolute path

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/pipes#68]
Using the instructions on https://github.com/ibm-cds-labs/pipes/wiki/Instructions-for-setting-up-a-local-dev-environment-for-Simple-Data-Pipe -- if you provide the environment variables (NODE_CONFIG, HOME) with absolute paths to the files, the system breaks.

I watched David debug this. He fixed this by adding `getAppRootDir();` to this block in his configManager.js:

```
//Load the nconfig
		var configPath = null;
		if ( path.isAbsolute( process.env.NODE_CONFIG ) ){
			getAppRootDir();
			configPath = process.env.NODE_CONFIG;
```

Sorry I'm a weirdo who used absolute paths to my vcap.json and pipes.json. Thanks! --Broberg

**Comment by DTAIEB** [comment]
Fixed on bluemix-helper-config module. You'll need to delete the node_modules/bluemix-helper-config dir and do another npm install

**Comment by mikebroberg** [comment]
Fixed! Thanks :dancer:
